version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-name: "@snapshot-labs/*"
    ignore:
      - dependency-name: "@snapshot-labs/checkpoint"
    groups:
      snapshot:
        patterns:
        - "@snapshot-labs/*"
